/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 color tokens (pink/rose theme)
        'md-primary': '#9b3f5a',
        'md-on-primary': '#ffffff',
        'md-primary-container': '#ff8fab',
        'md-primary-fixed': '#ffd9e0',
        'md-primary-fixed-dim': '#ffb1c2',
        'md-on-primary-fixed': '#3f0018',
        'md-secondary': '#146a5f',
        'md-on-secondary': '#ffffff',
        'md-secondary-container': '#a4f1e3',
        'md-secondary-fixed': '#a4f1e3',
        'md-secondary-fixed-dim': '#89d4c7',
        'md-on-secondary-container': '#1e7065',
        'md-tertiary': '#4d44e3',
        'md-on-tertiary': '#ffffff',
        'md-tertiary-container': '#aaa8ff',
        'md-tertiary-fixed': '#e2dfff',
        'md-on-tertiary-container': '#2f1dc9',
        'md-surface': '#fef8fa',
        'md-surface-bright': '#fef8fa',
        'md-surface-dim': '#ded9db',
        'md-surface-variant': '#e7e1e3',
        'md-surface-container-lowest': '#ffffff',
        'md-surface-container-low': '#f8f2f4',
        'md-surface-container': '#f2ecee',
        'md-surface-container-high': '#ece7e9',
        'md-surface-container-highest': '#e7e1e3',
        'md-on-surface': '#1d1b1d',
        'md-on-surface-variant': '#544245',
        'md-outline': '#877275',
        'md-outline-variant': '#dac0c4',
        'md-error': '#ba1a1a',
        'md-error-container': '#ffdad6',
        'md-on-error-container': '#93000a',
        'md-inverse-surface': '#323031',
        'md-inverse-on-surface': '#f5eff1',
        'md-inverse-primary': '#ffb1c2',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        jakarta: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        'pink-sm': '0 2px 8px rgba(255, 143, 171, 0.10)',
        'pink-md': '0 4px 16px rgba(255, 143, 171, 0.12)',
        'pink-lg': '0 8px 32px rgba(255, 143, 171, 0.16)',
        'pink-nav': '0 -4px 24px rgba(255, 143, 171, 0.10), 0 8px 32px rgba(0,0,0,0.06)',
        'pink-fab': '0 8px 24px rgba(155, 63, 90, 0.35)',
      },
    },
  },
  plugins: [],
}
